Add opt options rebase
Cambridge-ICCS/FTorch pull request #103
Opened 2024-03-28 20:24 UTC by jatkinson1000

This is an updated version of #78 rebased onto main after the GPU changes by @jwallwork23

@ElliottKasoar's comment on the original PR:

Resolves #73

Adds flags in all(?) functions that operate on tensors (tensor creation, model loading, forward) to optionally disable autograd, which should improve performance for inference.

Also adds a similar flag to set evaluation mode for the loaded model.

- Evaluation mode
  - Contrary to my initial comments in #73, from testing evaluation mode does appear to be preserved, both between saving and loading TorchScript, and when applied to the loaded model.
  - In most cases evaluation mode is therefore likely to already be set, but I think it's useful to have the option to change it, particularly if FTorch may be extended to facilitate training (#22).

- NoGradMode
  - Enabling or disabling gradients is more complicated, as it defined via a context manager, which only appears to define the behaviour within its own scope, and so it seems necessary to enable/disable gradients before every code block that operates on tensors (similar to the Python equivalent `with torch.no_grad():`).

- InferenceMode
  - No changes are currently included, but it would be good to support [InferenceMode](https://pytorch.org/cppdocs/notes/inference_mode.html) too eventually, as it should provide further performance benefits over NoGradMode.
  - However, it has stricter requirements, and the mode was only added (as a beta) in PyTorch 1.9, so we would need to be careful if we want to support older versions.

- Model freezing
  - No changes are currently included, and less directly applicable to the main FTorch library, although there are still interactions e.g. freezing the model can allow InferenceMode to be enabled when loading the model.
  - Freezing is currently the "default" when tracing in [pt2ts.py](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/pt2ts.py), but not for scripting, despite potentially [improving performance](https://pytorch.org/tutorials/prototype/torchscript_freezing.html).
  - Freezing appears to (sometimes) introduce numerical errors when saving the reloading (differences ~10^-6), and can seem to lead to issues loading with Forpy too.

(For more general explanation of autograd/evaluation mode, see [autograd mechanics](https://pytorch.org/docs/1.9.0/notes/autograd.html)).

Note: I've also removed the old, commented out `torch_from_blob` function.

2024-03-28 20:28 UTC, jatkinson1000 commented
Hi @ElliottKasoar after the work @jwallwork23 did there were some conflicts with your PR in #78.

I have done my best to rebase your work, but please could you take a look and see if everything seems in order to you?

@TomMelt You originally reviewed this PR and approved, but if you could take a quick glance and re-review it would be appreciated - since @jwallwork23 restructured the order of functions in the files and added additional arguments in the same place as @ElliottKasoar some of the merge conflicts got a little hairy so I may have missed the odd thing!

2024-03-28 20:33 UTC, jatkinson1000 commented
Before we merge we need to:

- [ ] Add some docs for these new options
- [ ] Add an example showing the use of these new options? 
        Or perhaps not given we are not training yet and just use the defaults...?

2024-04-02 09:32 UTC, jwallwork23 requested changes
Nice, seems like useful functionality.

Just a couple of comments that we need to address either by following my recommendations or by updating the `n_c_and_cpp` example to use the new API.

2024-04-02 09:32 UTC, jwallwork23 commented on src/ctorch.cpp
> +                           torch_device_t device_type, int device_index = -1, const bool requires_grad)
Should we provide a default value for `requires_grad` on the C++ side in the same way as for `device_index`? If not, should we reorder the arguments so that optional ones come last? (Similarly for other functions with this argument.)

I know this is already done on the Fortran side in this PR, but there may be users that want to use the C++ interface, too. Note that if `requires_grad` isn't made optional in this file then the draft example `n_c_and_cpp` will break because the API will change.

2024-04-02 09:32 UTC, jwallwork23 commented on src/ctorch.cpp
> +                                         const bool is_training)
Similarly, would it make sense to use a default value for `is_training`?

2024-04-02 14:37 UTC, ElliottKasoar requested changes
Thanks! Looks great other than a couple of places where I think the code may have got lost in the rebase (unless intentional?)

2024-04-02 14:37 UTC, ElliottKasoar commented on src/ftorch.fypp
> +    logical(c_bool)                :: requires_grad  !! Whether gradients need to be computed for the created tensor
```suggestion
    logical(c_bool)                :: requires_grad  !! Whether gradients need to be computed for the created tensor

    if (.not. present(requires_grad_opt)) then
      requires_grad = logical(.false., c_bool)
    else
      requires_grad = requires_grad_opt
    end if
```

2024-04-02 14:37 UTC, ElliottKasoar commented on src/ftorch.fypp
>    function torch_tensor_from_array_${PREC}$_${RANK}$d(data_in, layout, c_device_type, device_index) result(tensor)
```suggestion
  function torch_tensor_from_array_${PREC}$_${RANK}$d(data_in, layout, c_device_type, device_index, requires_grad_opt) result(tensor)
```

2024-04-02 14:39 UTC, ElliottKasoar commented on src/ctorch.cpp
> +                           torch_device_t device_type, int device_index = -1, const bool requires_grad)
I think at the time I may have been hesitant to introduce too many sources of defaults, but on reflection, yes I agree that adding the same defaults to the C++ side makes sense, especially to keep the pure C++ interface as an option.

2024-04-02 15:55 UTC, jatkinson1000 commented on src/ftorch.fypp
> +    logical(c_bool)                :: requires_grad  !! Whether gradients need to be computed for the created tensor
Nope - that's exactly why I wanted you to take a look!
Have committed the suggestions and will look at setting defaults later on.

2024-04-07 01:34 UTC, jatkinson1000 commented on src/ctorch.cpp
> +                           torch_device_t device_type, int device_index = -1, const bool requires_grad)
This should now be done in https://github.com/Cambridge-ICCS/FTorch/pull/103/commits/75b7aa0a246ede7e6c3cc0629939923941749543 if you are both happy with that?

2024-04-07 01:34 UTC, jatkinson1000 commented on src/ctorch.cpp
> +                                         const bool is_training)
This should now be done in https://github.com/Cambridge-ICCS/FTorch/pull/103/commits/75b7aa0a246ede7e6c3cc0629939923941749543 if you are both happy with that?

2024-04-08 08:11 UTC, jwallwork23 approved these changes
One minor point on formatting but otherwise looks good to me!

2024-04-08 08:11 UTC, jwallwork23 commented on src/ctorch.cpp
> +			                        torch_tensor_t output, const bool requires_grad=false)
This indentation looks like a typo?

2024-04-08 12:51 UTC, jatkinson1000 commented on src/ctorch.cpp
> +			                        torch_tensor_t output, const bool requires_grad=false)
No idea what is going on as it all looks fine locally in my vim!?!
Even checked they were spaces, not tabs.
Oh well, removed and reinserted and now it looks OK on here I think.

2024-04-08 13:11 UTC, jwallwork23 commented on src/ctorch.cpp
> +			                        torch_tensor_t output, const bool requires_grad=false)
How odd! Thanks.

2024-04-08 15:38 UTC, jatkinson1000 commented
Added a note to the FAQ about eval and no_grad settings.
A detailed example will perhaps wait until these are used as part of #111 since for now they are the sensible defaults for running inference.

Squashing and merging shortly.

2024-04-08 15:41 UTC, merged