Add developer guide page
Cambridge-ICCS/FTorch pull request #114
Opened 2024-04-08 21:50 UTC by jatkinson1000

This will close #106 

Adds guidance for developers:

- [ ] GitHub issues, forks, and PRs
- [ ] Using the hook
- [ ] fypp
- [ ] How to extend the API
- [ ] Documentation (FORD, and what to add)

2024-04-09 01:02 UTC, jatkinson1000 commented
Hi All, think this is ready for review.
@ElliottKasoar in particular let me know how it looks in response to #106

2024-04-09 08:42 UTC, jwallwork23 requested changes
Nice! A few suggested edits and additions.

2024-04-09 08:42 UTC, jwallwork23 commented on README.md
> +[online developer documentation](page/developer.html).
I think this should be `(pages/developer.html)`.

2024-04-09 08:42 UTC, jwallwork23 commented on pages/developer.md
> +[open an issue](https://github.com/Cambridge-ICCS/FTorch/issues).
Suggest this URL instead: https://github.com/Cambridge-ICCS/FTorch/issues/new/choose, given that the link here is used again in the next sentence anyway.

2024-04-09 08:42 UTC, jwallwork23 commented on pages/developer.md
> +* Modify `ftorch.fypp` to create a fortran version of the function
Fortran

2024-04-09 08:42 UTC, jwallwork23 commented on pages/developer.md
> +open-source contributions please get in touch!
Worth saying how to get in touch.

2024-04-09 08:42 UTC, jwallwork23 commented on pages/developer.md
> +by [Doxygen](https://www.doxygen.nl/index.html).
How to generate it from the source?

2024-04-09 09:08 UTC, TomMelt commented on pages/developer.md
> +open-source contributions please get in touch!
perhaps we should guide to opening a discussion rather than an email? emails tend to get stale v. quickly. Or we can think about an FTorch email... but that might be more effort.

2024-04-09 09:10 UTC, TomMelt commented on pages/developer.md
> +and many of our users wish to _"clone-and-go"_ rather than develop, we provide both.<br>
just curious why we have a line break (`<br>`) here but not really anywhere else. Was it from an editor. Will two newlines suffice? or am I missing something?

2024-04-09 09:11 UTC, jwallwork23 commented on pages/developer.md
> +open-source contributions please get in touch!
Yeah I agree, the recommended contact method should be via GitHub.

2024-04-09 09:13 UTC, TomMelt commented on pages/developer.md
> +after they have inspected it and are happy with its contents.
````suggestion
Use of the hook is not automatic and needs to be enabled by the developer (after they have inspected it and are happy with its contents). Hooks can be enabled with the following commands:
```
cp .githooks/pre-commit .git/hooks/
chmod +x .git/pre-commit
```
````

2024-04-09 09:18 UTC, TomMelt approved these changes
had some suggestions. They are all optional.

Thanks Jack :+1:

2024-04-09 09:18 UTC, TomMelt commented on pages/developer.md
> +* Match optional argument defaults between Fortran, C, and C++<br>
again `<br>` here too. Not big deal just curious.

2024-04-09 09:18 UTC, TomMelt commented on pages/developer.md
> +  Principle of Least Surprise.
```suggestion
* Match optional argument defaults between Fortran, C, and C++ ([principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)).
```

2024-04-09 10:19 UTC, ElliottKasoar commented on README.md
> +[online developer documentation](page/developer.html).
I think it is supposed to be `page`, but it's missing the rest of the URL? Should be `https://cambridge-iccs.github.io/FTorch/page/developer.html`, similar to `https://cambridge-iccs.github.io/FTorch/page/cmake.html` etc?

2024-04-09 15:22 UTC, jatkinson1000 commented on pages/developer.md
> +  Principle of Least Surprise.
I knew the acronym was POLA and couldn't figure out why it didn't match 😅

2024-04-09 15:33 UTC, jatkinson1000 commented on pages/developer.md
> +and many of our users wish to _"clone-and-go"_ rather than develop, we provide both.<br>
Issue with FORD where `\` doesn't to work for a line break.
Issue opened here: https://github.com/Fortran-FOSS-Programmers/ford/issues/646
I could perhaps use two trailing whitespaces, but am not keen on this as it is 'invisible' and sometimes get removed by over-zealous editors/IDEs.

Two newlines would be a full return rather than a break.

2024-04-09 15:35 UTC, jatkinson1000 commented on pages/developer.md
> +open-source contributions please get in touch!
I agree with Elliott - we have already had 2 - 3 people contact via email because they don't use GH.
Perhaps we use the ICCS email address as a catch-all with a request to forward to the RSE team?

2024-04-09 15:36 UTC, jatkinson1000 commented on README.md
> +[online developer documentation](page/developer.html).
In theory FORD can do local structure for links.
Did either of you check this with a local build?

2024-04-10 08:01 UTC, jatkinson1000 commented on README.md
> +[online developer documentation](page/developer.html).
Works on my local build so marking as resolved.

2024-04-10 08:03 UTC, jatkinson1000 commented on pages/developer.md
> +  Principle of Least Surprise.
This should be incorporated into https://github.com/Cambridge-ICCS/FTorch/pull/114/commits/403b2c752ce7610dec37ab5787a7a0406c133e84

2024-04-10 08:03 UTC, jatkinson1000 commented on pages/developer.md
> +after they have inspected it and are happy with its contents.
This should be incorporated into https://github.com/Cambridge-ICCS/FTorch/pull/114/commits/403b2c752ce7610dec37ab5787a7a0406c133e84

2024-04-10 08:04 UTC, jatkinson1000 commented on pages/developer.md
> +open-source contributions please get in touch!
Update in https://github.com/Cambridge-ICCS/FTorch/pull/114/commits/403b2c752ce7610dec37ab5787a7a0406c133e84 see if you're happy with this. Would prefer not to use a 'middle-person' emaiul, but also think it's better to use a persistent one rather than anyone's personal one.

2024-04-10 08:05 UTC, jatkinson1000 commented on pages/developer.md
> +* Modify `ftorch.fypp` to create a fortran version of the function
Damnitt!! Should be done in https://github.com/Cambridge-ICCS/FTorch/pull/114/commits/403b2c752ce7610dec37ab5787a7a0406c133e84

2024-04-10 08:05 UTC, jatkinson1000 commented on pages/developer.md
> +[open an issue](https://github.com/Cambridge-ICCS/FTorch/issues).
Should be done in https://github.com/Cambridge-ICCS/FTorch/commit/403b2c752ce7610dec37ab5787a7a0406c133e84

2024-04-10 08:11 UTC, jwallwork23 commented on pages/developer.md
> +open-source contributions please get in touch!
Looks good, thanks.

2024-04-10 08:12 UTC, jwallwork23 approved these changes
Thanks for the changes @jatkinson1000.

2024-04-10 09:10 UTC, TomMelt commented on pages/developer.md
> +open-source contributions please get in touch!
I agree with @ElliottKasoar too. That some people may not want to openly ask for help.

My issue with the ICCS email is none of us actually read it / have access... so there is high chance they get lost. Ideally we would need an FTorch specific email but this is more admin overhead to monitor and maintain.

Perhaps we stick to a personal email until we get something better :shrug:

2024-04-10 09:11 UTC, TomMelt commented on pages/developer.md
> +open-source contributions please get in touch!
so maybe Jack seeming as you are most active on Ftorch we use your email if you are happy with that?

If not I am happy to stick with ICCS email... but we need to either get access or make sure the maintainers of the email forward FTorch queries to us directly.

(unless you already have access and it's just me that doesn't)

2024-04-10 09:14 UTC, TomMelt commented on pages/developer.md
> +  Principle of Least Surprise.
thanks

2024-04-10 09:17 UTC, jatkinson1000 commented on pages/developer.md
> +open-source contributions please get in touch!
Yep, that's fine. Updated accordingly in https://github.com/Cambridge-ICCS/FTorch/pull/114/commits/e7afadd035aae25a301db52626a9b6725dc0c9f3.
I specify GitHub as the preferred option, and we can always update if required at a later stage.

2024-04-10 09:32 UTC, jatkinson1000 commented on pages/developer.md
> +by [Doxygen](https://www.doxygen.nl/index.html).
Something for future development.

2024-04-10 09:34 UTC, jatkinson1000 commented
@ElliottKasoar If you are happy and can remove your request changes I'll get this squashed and merged.

2024-04-10 10:02 UTC, ElliottKasoar approved these changes
Thanks again!

2024-04-10 10:07 UTC, merged