Handle multiple outputs from models.
Cambridge-ICCS/FTorch pull request #136
Opened 2024-06-12 12:00 UTC by jatkinson1000

Currently work in progress.

Requested by user in #135 

Definitely possible, but my C++-fu is not as strong as Fortran so currently stuck in pointer hell.

- [ ] Update C++ to process the option of multiple outputs
    - [ ] Inspect result to see if it is a tensor or tuple and handle accordingly
- [ ] Update Fortran to handle this
    - [ ] Make outputs a vector like inputs
    - [ ] Require n_out as argument to forward

Other thoughts:

- This will be a breaking API change for current users 😞 
- [ ] Should we make this an interface so users can pass a single tensor or an array of tensors?
- [ ] Can we somehow detect n_in? I have a feeling we looked before and the answer was no...

2024-06-17 10:56 UTC, jwallwork23 commented
Okay @jatkinson1000 @TomMelt @ma595 this is now working! Ready for review.

2024-06-21 06:53 UTC, jatkinson1000 reviewed
Thanks @jwallwork23 

This looks sensible to me, but please do double check the data copy aspect as you mentioned.
I can confirm things run as expected.

Remaining things would be to add documentation, and then make a final decision on what we want to to do with the API (probably in the opposite order!!) which we can discuss. Let me know if you want me to lend a hand with documentation.

I'm also noting that I can't approve this PR as I am a co-author, so will also need @TomMelt to take a look.

2024-06-21 06:53 UTC, jatkinson1000 commented on examples/3_MultiGPU/CMakeLists.txt
> +target_link_libraries(simplenet_infer_fortran_gpu PRIVATE MPI::MPI_Fortran)
I feel like ideally this change would be made in a different PR as it is not related to the subject of this PR (as far as I can tell, is it to do with a name clash when building tests?).
Easiest to leave it in here now.

2024-06-21 06:53 UTC, jatkinson1000 commented on examples/4_MultiIO/README.md
I'm sure you are aware, but just flagging that this will need completing.

2024-06-21 06:53 UTC, jatkinson1000 commented on src/ctorch.cpp
> +    }
On data transfers, I am not a C++ expert, but I think the only dangerous step here is whether `.toTensor()` or `.toTuple()` create data copies.
That said, I think this mirrors the previous approach.
Let me know your thoughts.

2024-06-21 06:53 UTC, jatkinson1000 commented on utils/pt2ts.py
> +            )
Thank you for including this change!!

2024-06-24 10:06 UTC, TomMelt commented on src/ctorch.cpp
> +    }
Hi @jatkinson1000 , according to the PyTorch API docs I don't think that the `toX()` methods create a copy.

> IValues are used as inputs to and outputs from the TorchScript interpreter. To retrieve the value contained within an [IValue](https://pytorch.org/cppdocs/api/structc10_1_1_i_value.html#structc10_1_1_i_value), use the .toX() methods, where X is the type you are trying to get. Note that neither the .toX() methods nor the templated .to<T> functions do any kind of casting, they only unwrap the contained value.

see https://pytorch.org/cppdocs/api/structc10_1_1_i_value.html#struct-documentation for more details.

2024-06-25 08:41 UTC, jatkinson1000 commented on src/ctorch.cpp
> +    }
Perfect, in that case I think we are all good!

2024-06-25 09:29 UTC, TomMelt requested changes
Looks good. Just a couple of things to discuss

2024-06-25 09:29 UTC, TomMelt commented on examples/4_MultiIO/CMakeLists.txt
> +    "   0.00000000      -3.00000000      -6.00000000      -9.00000000")
these tests will most likely fail with the intel compiler and possibly different version of `gfortran`. The default output is quite different for both. We should think of another way to do this.

We could add something like the resnet test?

https://github.com/Cambridge-ICCS/FTorch/blob/b40b03d4c39f607de754d34991a92703ccc36eb3/examples/2_ResNet18/resnet_infer_fortran.f90#L186C15-L214

2024-06-25 09:29 UTC, TomMelt commented on examples/4_MultiIO/pt2ts.py
> +    # FPTLIB-TODO
what do these comments refer to (`FPTLIB-TODO`). Is it for documentation?

2024-06-25 09:29 UTC, TomMelt commented on examples/4_MultiIO/pt2ts.py
> +    ## print(frozen_model.code)
can we remove these comments

2024-06-25 09:29 UTC, TomMelt commented on examples/4_MultiIO/pt2ts.py
> +    # print(scripted_model.code)
same here

2024-06-25 09:29 UTC, TomMelt commented on examples/4_MultiIO/simplenet_infer_fortran.f90
> +   write (*,*) out_data2
if you want to keep the regex check for CMake test we can force the output formatting here. See e.g., https://web.stanford.edu/class/me200c/tutorial_77/17_format.html

Perhaps this?
```suggestion
   write (*,'(4(f8.3))') out_data1
   write (*,'(4(f8.3))') out_data2
```

2024-06-25 09:29 UTC, TomMelt commented on examples/4_MultiIO/simplenet_infer_fortran.f90
> +   write (*,*) out_data2
This will (should) give the same output and be compiler agnostic.

2024-06-25 10:09 UTC, jatkinson1000 commented on examples/4_MultiIO/pt2ts.py
> +    # FPTLIB-TODO
They signify to the user where they need to edit the guidance script `pt2ts.py` to export their particular net to TorchScript. I don't think they need changing here.

2024-06-25 10:10 UTC, jatkinson1000 commented on examples/4_MultiIO/pt2ts.py
> +    ## print(frozen_model.code)
I think they are a pull over from the `pt2ts.py` script where they are an option for the user to check that they are running things correctly. I would erro on leaving them in for consistency with the base `pt2ts.py`, but open to a discussion.

2024-06-25 10:10 UTC, jatkinson1000 commented on examples/4_MultiIO/pt2ts.py
> +    # print(scripted_model.code)
As above.

2024-06-25 10:14 UTC, jatkinson1000 commented on examples/4_MultiIO/simplenet_infer_fortran.f90
> +   write (*,*) out_data2
@jwallwork23 This falls under testing so do you want to cover this?
I would also consider opening a separate issue and PR to enact this in the other examples as it is not directly related to this PR.

2024-06-25 10:22 UTC, jatkinson1000 commented on examples/4_MultiIO/CMakeLists.txt
> +    "   0.00000000      -3.00000000      -6.00000000      -9.00000000")
Setting the output to `PASS` or `FAIL` and reading that would probably be a sensible approach, I agree.
I would encourage doing this for the other exercises in a separate PR, however.

2024-06-25 10:53 UTC, jwallwork23 commented on examples/4_MultiIO/CMakeLists.txt
> +    "   0.00000000      -3.00000000      -6.00000000      -9.00000000")
I agree, that would be a better approach indeed. I opened a new issue for this: #142.

2024-06-25 11:50 UTC, jwallwork23 commented on examples/4_MultiIO/README.md
Apologies - done now in d3abc449bd3dafbcee18fd8ac402a67341551008.

2024-06-26 14:34 UTC, jwallwork23 commented
Updated docs - ready for re-review.

2024-06-26 15:34 UTC, TomMelt commented on examples/4_MultiIO/CMakeLists.txt
> +    "   0.00000000      -3.00000000      -6.00000000      -9.00000000")
ok we can fix this at a later stage :ok_hand:

2024-06-26 15:39 UTC, TomMelt commented on examples/4_MultiIO/pt2ts.py
> +    ## print(frozen_model.code)
My general opinion is don't leave commented code in repos but in this case it's not a deal breaker.

I guess the ideal scenario is it's either worth keeping (i.e., refactored with a debug flag for example) or it's junk. The problem is, commented code doesn't get tested or updated. So it can get stale quickly :grimacing:

2024-06-26 15:42 UTC, TomMelt approved these changes
Thanks @jatkinson1000 and @jwallwork23 for this PR. It is a great addition to the code.

2024-06-26 15:42 UTC, merged

2024-06-26 20:47 UTC, jatkinson1000 commented
@TomMelt It seems like this was merged somewhat prematurely.
As a result I am having to update the README over in #143 to cover some of the changes made here which is not ideal.