Melt windows fix
Cambridge-ICCS/FTorch pull request #137
Opened 2024-06-19 12:01 UTC by TomMelt

fixes #124 

This is currently wip. It needs to be tested by end user.

If this fixes the problem I will tidy up the int64 issue and we can merge this PR in.

Tasks:
- [x] fix cmake windows build issue
- [ ] fix int64 issue properly

2024-09-09 09:08 UTC, jatkinson1000 commented
Discussion:

- For the places we have int we replace by an explicit int64 (or similar).
- This will remove the issues on Windows where we get a mismatch.
- Ensure docs are updated to be clear users now need to specify the type of int.
- This will allow this to be closed, and relates to #124 and #140

2024-11-19 09:38 UTC, jwallwork23 requested changes
This all looks reasonable and in agreement with what we discussed in the meeting, thanks!

The remaining thing to do is to document this, as mentioned in the checklist for the PR.

2024-11-19 09:51 UTC, jatkinson1000 requested changes
Discussed in meeting, small comments on looking at the code, looks like just docs left.

2024-11-19 09:51 UTC, jatkinson1000 commented on src/CMakeLists.txt
> +
A small comment to explain presence of this clause?

2024-11-19 09:51 UTC, jatkinson1000 commented on src/ftorch.fypp
> +    integer(ftorch_int)           :: i
```suggestion
    integer(ftorch_int)       :: i
```
Nit

2024-11-19 09:53 UTC, TomMelt commented
> This all looks reasonable and in agreement with what we discussed in the meeting, thanks!
> 
> The remaining thing to do is to document this, as mentioned in the checklist for the PR.

thanks. Just done in https://github.com/Cambridge-ICCS/FTorch/pull/137/commits/d64358c7cb5d3a6c0c2427b1168a96d05cd01e94

2024-11-19 10:02 UTC, TomMelt commented on src/CMakeLists.txt
> +
done in https://github.com/Cambridge-ICCS/FTorch/pull/137/commits/b3b50a16dc2563682470924e065e62e20f8bcad0

2024-11-19 10:03 UTC, TomMelt commented on src/ftorch.fypp
> +    integer(ftorch_int)           :: i
I did one better. See https://github.com/Cambridge-ICCS/FTorch/pull/137/commits/594e9386338a4ba348b80fdbffe8ed3e07968ae7. Hope you like it :crossed_fingers:

2024-11-21 13:38 UTC, jwallwork23 approved these changes
Thanks for adding the docs, @TomMelt. Just one minor request then good to go!

2024-11-21 13:38 UTC, jwallwork23 commented on pages/troubleshooting.md
> +Finally, you will need to run `fypp` e.g.,
I guess users may also need to install this because it isn't in the set of minimal requirements.

2024-11-21 13:38 UTC, jwallwork23 commented on pages/troubleshooting.md
> +fypp src/ftorch.fypp > src/ftorch.F90
Not important but FYI this also works without the `>`.

2024-11-21 13:52 UTC, TomMelt commented on pages/troubleshooting.md
> +fypp src/ftorch.fypp > src/ftorch.F90
Thanks @jwallwork23 TIL.

2024-12-09 15:54 UTC, TomMelt commented on pages/troubleshooting.md
> +Finally, you will need to run `fypp` e.g.,
resolved https://github.com/Cambridge-ICCS/FTorch/pull/137/commits/5cdfe22df277c84b410914ea4df4171c0cecc9df

2024-12-09 15:54 UTC, TomMelt commented on pages/troubleshooting.md
> +fypp src/ftorch.fypp > src/ftorch.F90
changed to your version... it saves 1 character :wink: https://github.com/Cambridge-ICCS/FTorch/pull/137/commits/5cdfe22df277c84b410914ea4df4171c0cecc9df

2024-12-09 17:13 UTC, jatkinson1000 approved these changes
Couple of suggestions on phrasing, but not blocking.
Should be OK with this being added once #168 is approved and merged

2024-12-09 17:13 UTC, jatkinson1000 commented on pages/troubleshooting.md
> +compile time error like the following:
Add small explanation as to why we made the decision.
```suggestion
Currently FTorch represents the number of elements in an array dimension using
32-bit integers. For most users this will be more than enough, but if your code
uses large tensors (where large means more than 2,147,483,647 elements
in any one dimension (the maximum value of a 32-bit integer)), you may you may
need to compile `ftorch` with 64-bit integers. If you do not, you may receive a
compile time error like the following:
```

2024-12-10 15:06 UTC, TomMelt commented
the only test that fails is in the static analysis when running `fortitude`. This will be fixed separately by #205

2024-12-10 15:06 UTC, merged