Adjust the API in anticipation of future overloading
Cambridge-ICCS/FTorch pull request #143
Opened 2024-06-26 07:15 UTC by jatkinson1000

Change the API to make assignment of data to a `torch_tensor` a subroutine.

This is in anticipation of the AutoGrad wotk led by @jwallwork23 in #139 
This work may take a while to complete, but we need to stablise the API in advance of the summer school and as we move towards a first release and JOSS.

This makes the changes to the API that are required for this work without changing anything underneath.

2024-06-26 07:44 UTC, jatkinson1000 commented
One thought @jwallwork23 and @TomMelt:

After this most things will be subroutines to be `call`ed from Fortran.

Do we want to update the module loading to be:
```
torch_module_load(torch_model, filename, device_type)
```
rather than:
```
torch_model = torch_module_load(filename, device_type)
```
?

And do we want to make it `torch_model_load()` rather than `torch_module_load`?
I have had a couple of comments in the past about people misunderstanding what is meant by 'module' in this context (A Neural Net subclassed from PyTorch's `nn.Module`).

2024-06-26 08:03 UTC, dorchard commented on src/ftorch.f90
> +    type(torch_tensor), value, intent(in) :: tensor  !! Input tensor
Why do we need this to be pass-by-value here for get_device_index? Won't this create an unnecessary copy. I don't think torch_tensor_get_device_index would do any modification but is there another reason?

2024-06-26 08:05 UTC, dorchard commented
I like the naming of `torch_model_load` - it might indeed be more clear.

2024-06-26 08:11 UTC, jatkinson1000 commented on src/ftorch.f90
> +    type(torch_tensor), value, intent(in) :: tensor  !! Input tensor
This was a change @jwallwork23 made so he can advise.
It may be that is is unnecessary for this part but required in the overloading for some reason.

2024-06-26 10:45 UTC, jwallwork23 commented on src/ftorch.f90
> +    type(torch_tensor), value, intent(in) :: tensor  !! Input tensor
You're right, this isn't needed. Thanks @dorchard.

2024-06-26 10:48 UTC, jwallwork23 commented
Thanks very much for this @jatkinson1000! I was going to suggest doing this separately, too.

> Do we want to update the module loading to be:
> 
> ```
> call torch_module_load(torch_model, filename, device_type)
> ```
> 
> rather than:
> 
> ```
> torch_model = torch_module_load(filename, device_type)
> ```

Once the assignment operator is overloaded for tensors, any function that returns a tensor will implicitly do an additional copy, so it's probably best to turn any functions that return tensors into subroutines.
 
> And do we want to make it `torch_model_load()` rather than `torch_module_load`?

I agree with @dorchard that `torch_model_load` is clearer.

2024-06-26 12:45 UTC, jatkinson1000 commented on src/ftorch.f90
> +    type(torch_tensor), value, intent(in) :: tensor  !! Input tensor
Coolio, I'll remove in due course.

2024-06-26 20:20 UTC, jatkinson1000 commented on src/ftorch.f90
> +    type(torch_tensor), value, intent(in) :: tensor  !! Input tensor
Should be covered in https://github.com/Cambridge-ICCS/FTorch/pull/143/commits/7a35805a56139a2209301fd31c619dce9608913a

2024-06-26 20:22 UTC, jatkinson1000 commented
The latest commits refer to the model as a '`model`' rather than a `module` (note that it still has to be referred to as a module when binding to C++ as this is what the Torch API uses).

It also makes the module loading a subroutine rather than a function.
I have left the get device as a function as this feels more appropriate in this instance.

2024-06-27 08:18 UTC, dorchard requested changes
Looks good but a couple of documentation updates needed. Also [pages/troubleshooting.md] has a left over `torch_module_forward`

2024-06-27 08:18 UTC, dorchard commented on README.md
> +call torch_module_load(model, "/my/saved/TorchScript/model.pt")
should be `torch_model_load`

2024-06-27 08:18 UTC, dorchard commented on README.md
> +call torch_module_forward(model, model_input_arr, model_output_arr)
should be `torch_model_forward`

2024-06-27 08:38 UTC, dorchard commented on README.md
> +call torch_module_load(model, "/my/saved/TorchScript/model.pt")
```suggestion
call torch_model_load(model, "/my/saved/TorchScript/model.pt")
```

2024-06-27 08:38 UTC, dorchard commented on README.md
> +call torch_module_forward(model, model_input_arr, model_output_arr)
```suggestion
call torch_model_forward(model, model_input_arr, model_output_arr)
```

2024-06-27 08:39 UTC, dorchard requested changes
Update API in documentation

2024-06-27 09:10 UTC, jatkinson1000 commented on README.md
> +call torch_module_forward(model, model_input_arr, model_output_arr)
Should be covered in a sneaky rebase: https://github.com/Cambridge-ICCS/FTorch/pull/143/commits/8c1c98b68990c68202fb8a5e7e4fe1dffb46d96e

2024-06-27 09:10 UTC, jatkinson1000 commented on README.md
> +call torch_module_load(model, "/my/saved/TorchScript/model.pt")
Should be covered in a sneaky rebase: https://github.com/Cambridge-ICCS/FTorch/pull/143/commits/8c1c98b68990c68202fb8a5e7e4fe1dffb46d96e

2024-06-27 09:11 UTC, jatkinson1000 commented
Thanks @dorchard I have addressed those in a rebase to keep history clean.
Ready for a re-review I think.

2024-06-27 09:13 UTC, dorchard approved these changes
lgtm.

2024-06-27 10:40 UTC, jwallwork23 approved these changes
Approved with one minor optional request and a comment.

2024-06-27 10:40 UTC, jwallwork23 commented on examples/1_SimpleNet/simplenet_infer_fortran.f90
> -   model = torch_module_load(args(1))
This wouldn't be affected by overloading of tensors, but I guess it's good to be consistent.

2024-06-27 10:40 UTC, jwallwork23 commented on examples/3_MultiGPU/simplenet_infer_fortran.f90
> +                           torch_kCUDA, device_index=rank)
Inconsistent indentation

2024-06-27 11:16 UTC, jatkinson1000 commented on examples/1_SimpleNet/simplenet_infer_fortran.f90
> -   model = torch_module_load(args(1))
Yes, see discussion further up.

Also see that I have left `get_device_index` as a function as that feels more appropriate.

2024-06-27 11:18 UTC, jatkinson1000 commented on examples/3_MultiGPU/simplenet_infer_fortran.f90
> +                           torch_kCUDA, device_index=rank)
Should be addressed in https://github.com/Cambridge-ICCS/FTorch/pull/143/commits/bfbbce9e3976df19615315589e3f163aa04cc0e7

2024-06-27 11:19 UTC, merged