Implement `torch_tensor_to_array`
Cambridge-ICCS/FTorch pull request #161
Opened 2024-07-22 17:03 UTC by jwallwork23

Closes #151.

Implements `torch_to_blob` on the C++ side and `torch_tensor_to_array` on the Fortran side.

Updates example 1 to use this.

2024-07-23 06:32 UTC, jatkinson1000 reviewed
Looking good @jwallwork23 

I have a question about the update to example 1 - presumably the use of `torch_tensor_to_array` is redundant here if you had not also changed the `out_data` to `pointer`?

My feeling is that this adds additional layers of confusion and is not what this example is intended to show as people's first entry point to FTorch. Perhaps there could be a separate example for introducing the autograd features?

Apologies if I have misunderstood and this is a change that is required across all of the code!

2024-07-23 08:34 UTC, jwallwork23 commented
> I have a question about the update to example 1 - presumably the use of `torch_tensor_to_array` is redundant here if you had not also changed the `out_data` to `pointer`?

Agreed. I was planning to switch this to `torch_tensor_empty`, but this hasn't been implemented yet.

> My feeling is that this adds additional layers of confusion and is not what this example is intended to show as people's first entry point to FTorch. Perhaps there could be a separate example for introducing the autograd features?

Yeah, fair enough. Perhaps this PR could start the autograd demo as just "to tensor" and then "to array".

2024-07-23 11:06 UTC, jwallwork23 commented
This is now ready for review, with thanks to @TomMelt for input on the C++ side.

2024-07-23 11:11 UTC, jwallwork23 commented on src/ctorch.cpp
> +    exit(EXIT_FAILURE);
This is assuming the `not supported in Fortran` comment on the Fortran side is accurate.

2024-07-23 11:11 UTC, jwallwork23 commented on src/ctorch.cpp
> +    exit(EXIT_FAILURE);
Similarly here.

2024-07-23 16:20 UTC, jatkinson1000 reviewed
Thanks @jwallwork23 left you a couple of comments on there.

2024-07-23 16:20 UTC, jatkinson1000 commented on src/ctorch.cpp
> +    exit(EXIT_FAILURE);
Consider making the error message more specific: "uint8 not supported in Fortran"?

2024-07-23 16:20 UTC, jatkinson1000 commented on src/ctorch.cpp
> +    exit(EXIT_FAILURE);
Consider making the error message more specific: "float16 not supported in Fortran"?

2024-07-23 16:20 UTC, jatkinson1000 commented on src/ctorch.cpp
> +      break;
Is it worth a comment somewhere to note this in case we end up having a use case in future?
I agree at the moment we don't want C++23!

2024-07-23 16:20 UTC, jatkinson1000 commented on examples/5_Autograd/requirements.txt
This file is empty, can it be removed, or should it have `torch` in there?

2024-07-23 16:20 UTC, jatkinson1000 commented on examples/5_Autograd/autograd.f90
> +  allocate(out_data(2))
I wonder if it is possible/sensible to hide away this `allocate` within `torch_tensor_from_array`?
Or whether users should be expected to provide `out_data` to be the correct size as expected.

2024-07-23 16:20 UTC, jatkinson1000 commented on examples/5_Autograd/README.md
Sounds like a good plan!

2024-07-23 17:31 UTC, jwallwork23 commented on examples/5_Autograd/requirements.txt
It's required by the `run_integration_tests.sh` script and the `.github/workflows/test_suite.yml` workflow, both of which attempt to pip install the dependencies.

Either we keep this empty file or we change those to only install if the file exists.

2024-07-23 17:47 UTC, jwallwork23 commented on examples/5_Autograd/autograd.f90
> +  allocate(out_data(2))
IIRC with `pointer` arrays you can't provide a size at declaration - they need to be allocated.

Yes, we could handle the allocation inside `torch_tensor_to_array` (presumably you meant this subroutine?). It will mean adding a `layout` argument, which is a good idea anyway as it improves consistency with `torch_tensor_from_array`. I'll implement it using an `if (.not. allocated(data_out)) ...` condition and a shape check, in case a user already allocated the array themselves.

2024-07-23 17:48 UTC, jwallwork23 commented on src/ctorch.cpp
> +    exit(EXIT_FAILURE);
Addressed in 806730c55e03b06ff48aa96ec13e4467d9b2a99e.

2024-07-23 17:48 UTC, jwallwork23 commented on src/ctorch.cpp
> +    exit(EXIT_FAILURE);
Addressed in 806730c55e03b06ff48aa96ec13e4467d9b2a99e.

2024-07-23 17:48 UTC, jwallwork23 commented on src/ctorch.cpp
> +      break;
Good idea. Addressed in 0f6ee05722b051f0a989dd0f535e4584efd7ff60.

2024-07-24 09:15 UTC, jwallwork23 commented on examples/5_Autograd/autograd.f90
> +  allocate(out_data(2))
Addressed in https://github.com/Cambridge-ICCS/FTorch/pull/161/commits/e2f6a9d473af461540de51ec64544d53728a9e92.

2024-09-13 13:59 UTC, jatkinson1000 requested changes
Thanks, @jwallwork23 

Code all looks good, but as discussed in-person a little more explanation in the comments around the tensor_to_array function would be useful please.

2024-09-13 13:59 UTC, jatkinson1000 commented on src/ftorch.fypp
> +    end if
As discussed in-person, this is somewhat nuanced from the way we interact with libtorch, and potential for having data that will be pointed to by an currently unallocated variable.

Slightly more detail in the comments to explain what/why we are doing will help when coming back to this in future.

2024-09-13 14:02 UTC, jwallwork23 commented on src/ftorch.fypp
> +    end if
Thanks, should be addressed in 570bf21.

2024-09-13 14:32 UTC, jatkinson1000 approved these changes
Yep, this is very clear now. Thanks @jwallwork23

2024-09-13 14:34 UTC, merged