WIP: Windows ci build
Cambridge-ICCS/FTorch pull request #168
Opened 2024-09-13 15:38 UTC by TomMelt

This is WIP. Trying to make a windows CI build

2024-12-03 16:02 UTC, jatkinson1000 reviewed
Thanks @TomMelt
Looks sensible to me (as much as any windows code does...)

I think we need some documentation adding about how to run the test suite for Windows users (definitely online and maybe README, though perhaps online only to avoid pollution)

I know nothing about bat scripts, but is there a reason we apply it in a for loop for each example as part of the workflow rather than running all examples from the bat script as we do in `run_integration_tests.sh`?

2024-12-04 09:43 UTC, jwallwork23 requested changes
Thanks for putting in the effort to get this working @TomMelt. Just a few minor comments from me.

2024-12-04 09:43 UTC, jwallwork23 commented on .github/workflows/test_suite_windows.yml
> +  pull_request:
Please could you add comments consistently as in the other workflows? My recent workflow PR made them all similar in this respect.

2024-12-04 09:43 UTC, jwallwork23 commented on .github/workflows/test_suite_windows.yml
> +          for /d %%i in (1_SimpleNet 2_ResNet18 4_MultiIO) do ..\run_integration_tests.bat build\test\examples\%%i
Same question as @jatkinson1000 - can this loop not go inside the `run_integration_tests.bat` script?

2024-12-04 09:43 UTC, jwallwork23 commented on run_integration_tests.bat
> +popd
This file needs some comments at the top to say what it is (i.e., that it's the Windows version of `run_integration_tests.sh`.

2024-12-09 09:52 UTC, jwallwork23 commented on .github/workflows/test_suite_windows.yml
Perhaps rename the other one to `test_suite_ubuntu.yml` for clarity. We could use reusable workflows to make it easier if we ever want to add another test workflow. I can look into this as a follow-up.

2024-12-09 09:56 UTC, jwallwork23 commented on .github/workflows/test_suite_windows.yml
Opened #201 and self-assigned.

2024-12-09 11:27 UTC, TomMelt commented on .github/workflows/test_suite_windows.yml
> +  pull_request:
fixed by [d177685](https://github.com/Cambridge-ICCS/FTorch/pull/168/commits/d177685da3263399d49e3b0deb2c57d4dcf66fde)

2024-12-09 11:28 UTC, TomMelt commented on .github/workflows/test_suite_windows.yml
> +          for /d %%i in (1_SimpleNet 2_ResNet18 4_MultiIO) do ..\run_integration_tests.bat build\test\examples\%%i
fixed by [a6ec9c2](https://github.com/Cambridge-ICCS/FTorch/pull/168/commits/a6ec9c2ef7d8e880b5d0efabee8737d24ff5f3e1)

2024-12-09 11:28 UTC, TomMelt commented
> I know nothing about bat scripts, but is there a reason we apply it in a for loop for each example as part of the workflow rather than running all examples from the bat script as we do in `run_integration_tests.sh`?

fixed by [a6ec9c2](https://github.com/Cambridge-ICCS/FTorch/pull/168/commits/a6ec9c2ef7d8e880b5d0efabee8737d24ff5f3e1)

2024-12-09 11:37 UTC, jwallwork23 commented on .github/workflows/test_suite_windows.yml
> +      - '.github/workflows/test_suite.yml'
This should be specific to the `test_suite_windows.yml` config.

Similar change in `test_suite_ubuntu.yml` if it's renamed as such.

2024-12-09 11:57 UTC, TomMelt commented on src/CMakeLists.txt
> +  if (WIN32)
resolved by #203

2024-12-09 11:57 UTC, TomMelt commented on run_integration_tests.bat
> +popd
resolved by b38397a

2024-12-09 12:22 UTC, jwallwork23 approved these changes
Looks good!

2024-12-09 13:38 UTC, jatkinson1000 requested changes
Thanks @TomMelt This looks great, I think we just need the online documentation updating to match (in `pages/` - definitely `testing.md`, but worth a quick scan of anywhere else, including the Windows specific docs).

2024-12-09 13:38 UTC, jatkinson1000 commented on src/test/README.md
> +run the tests.
I wonder if we should clarify _Python_ dependencies (don't think there are any others??) and so it is advisable to be in a venv?

2024-12-09 15:26 UTC, TomMelt commented
> Thanks @TomMelt Looks sensible to me (as much as any windows code does...)
> 
> I think we need some documentation adding about how to run the test suite for Windows users (definitely online and maybe README, though perhaps online only to avoid pollution)
> 
> I know nothing about bat scripts, but is there a reason we apply it in a for loop for each example as part of the workflow rather than running all examples from the bat script as we do in `run_integration_tests.sh`?

solved by #203 and https://github.com/Cambridge-ICCS/FTorch/commit/b38397a8f3c7311fc1466f4490dd1d34665e2acb

2024-12-09 15:48 UTC, TomMelt commented on src/test/README.md
> +run the tests.
resolved by 4a23616

2024-12-09 16:50 UTC, jatkinson1000 requested changes
Thanks @TomMelt 

This is really great, and a significant hurdle - hopefully you learnt something useful, even if it is at the cost of becoming the "Windows guy". ;P 

The blocker for me is not only just to bump the version of CMake required by FTorch to be 3.15 (for use of the Python VIRTUALENV) feature (see specific comment).
Consider also updating in the example CMakeLists for consistency, and in the documentation. From past experience the easiest way to do this is to grep the full source for `3.5`.

Once that is done I am happy to approve.

Other question is whether there is anything you feel is particularly useful or unintuitive to highlight for Windows users within the workflow. Otherwise we can just update the Windows docs piece by piece as people raise things in future.

2024-12-09 16:50 UTC, jatkinson1000 commented on src/CMakeLists.txt
> +  set (Python3_FIND_VIRTUALENV FIRST)
This is a CMake 3.15 feature, so perhaps we need to bump the dependency across FTorch to CMake 3.15?

I think this is still sufficiently old not to be an issue for any users.

2024-12-10 11:46 UTC, TomMelt commented on src/CMakeLists.txt
> +  set (Python3_FIND_VIRTUALENV FIRST)
done in https://github.com/Cambridge-ICCS/FTorch/pull/168/commits/17d8db2589376ee4c0e5d92c9f99c38cba5720ba

2024-12-10 11:48 UTC, TomMelt commented
> Thanks @TomMelt
> 
> This is really great, and a significant hurdle - hopefully you learnt something useful, even if it is at the cost of becoming the "Windows guy". ;P
> 
> The blocker for me is not only just to bump the version of CMake required by FTorch to be 3.15 (for use of the Python VIRTUALENV) feature (see specific comment). Consider also updating in the example CMakeLists for consistency, and in the documentation. From past experience the easiest way to do this is to grep the full source for `3.5`.
> 
> Once that is done I am happy to approve.
> 
> Other question is whether there is anything you feel is particularly useful or unintuitive to highlight for Windows users within the workflow. Otherwise we can just update the Windows docs piece by piece as people raise things in future.

Thanks @jatkinson1000 , I have added a [concrete example](https://github.com/Cambridge-ICCS/FTorch/pull/168/commits/e7ebd4d9db1d8505566f574fb4a00840620db9da) to the online docs just in case anyone has difficulty (most likely my future self)

2024-12-10 14:27 UTC, TomMelt commented
> Thanks @TomMelt I think README.md and /pages/cmake.md still need the CMake versioin updating from 3.5 to 3.15.

done in https://github.com/Cambridge-ICCS/FTorch/pull/168/commits/df5340a595e9d4dad767aac2631c4d7e9ed339ca

2024-12-10 14:35 UTC, jatkinson1000 approved these changes
I'm happy with this now.

Thanks @TomMelt it has been a mammoth task you've done here!

2024-12-10 14:41 UTC, merged