Update README.md to add windows docs
Cambridge-ICCS/FTorch pull request #48
Opened 2023-10-16 14:28 UTC by mondus

Adds details of

- [x] How to install Intel Fortran in Windows
- [x] Details on obtaining the `CMAKE_PREFIX_PATH`
- [x] Cross platform build and install commands

2023-10-16 15:15 UTC, jatkinson1000 requested changes
Thanks @mondus a couple of small tweaks and a question about the install command.
I've forwarded it to the user and will see how he gets on - using `cmake --build` rather than `make` may be important!

2023-10-16 15:15 UTC, jatkinson1000 commented on README.md
> +    cmake --build . --target INSTALL
Does the former just make/build and the latter makes/builds and then installs?
Is `INSTALL` a keyword for CMake - I have only ever see it used lower case - https://cmake.org/cmake/help/latest/manual/cmake.1.html#build-a-project

2023-10-16 16:36 UTC, jatkinson1000 commented on README.md
> +    cmake --build . --target INSTALL
On reading looks like `install` is for makefile generators, whilst `INSTALL` is for GUI based systems: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Install.html

Will update accordingly and then merge when appropriate.

2023-10-19 07:35 UTC, jatkinson1000 commented
This is WIP with #50 
Once that is resolved with the user we will update here accordingly and then merging will close #50

2023-11-19 16:34 UTC, jatkinson1000 commented
I think this is good to go now (correspondent from #50 has gone quiet, but it works for us).
Since I have done a lot of this PR I will let @TomMelt do a final review for approval.

2023-11-20 09:58 UTC, TomMelt submitted a review, later dismissed
looks good to me. Just a couple of questions

2023-11-20 09:58 UTC, TomMelt commented on README.md
> +```makefile
I think this should technically be "```bash"

2023-11-20 10:48 UTC, jatkinson1000 commented on examples/2_ResNet18/README.md
> +cmake --build .
Yes.

2023-11-20 10:50 UTC, jatkinson1000 commented on README.md
> +```makefile
Done

2023-11-21 18:44 UTC, TomMelt commented
just added a note about loading intel compilers. If @mondus is happy then I think we can merge it in.

2023-11-21 18:54 UTC, jatkinson1000 commented
> just added a note about loading intel compilers. If @mondus is happy then I think we can merge it in.

@TomMelt Would it be worth extending that by telling users that this can usually be done by running `C:\Program Files (x86)\Intel\oneAPI\setvars` from Cmd?

2023-11-22 10:25 UTC, mondus reviewed
Tested in Windows. All good. Happy to approve. One minor suggestion comment to add a link to Intel guide on setvars.

2023-11-22 10:25 UTC, mondus commented on README.md
> +    intel fortran compilers using `setvars.bat` which is found in the Intel compiler install directory.
```suggestion
    intel fortran compilers using `setvars.bat` ([see Intel docs](https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2023-2/use-the-setvars-script-with-windows.html)) which is found in the Intel compiler install directory.
```

2023-11-22 10:33 UTC, jatkinson1000 commented
Thanks @mondus, that also addresses my comment above but in an even safer/better way than suggested, thanks.
I'll approve and merge now (@mondus has confirmed offline that he is happy with the PR).

2023-11-22 11:00 UTC, jatkinson1000 approved these changes
Thanks all who contributed here, I'm now happy to go ahead so will merge in a moment.

2023-11-22 11:01 UTC, merged