add mwe for fypp preprocessor
Cambridge-ICCS/FTorch pull request #60
Opened 2023-11-03 17:08 UTC by TomMelt

this example generates multiple variants of a function `torch_tensor_from_array_c_*` depending on data type and rank of input data.

We should discuss how we actually want to implement this.

When this is finished it will close #58

2023-11-06 11:57 UTC, TomMelt commented
I need to make a fortran-only interface with a mwe that removes the need for the end user to import `iso_c_bindings`

2023-11-06 17:25 UTC, ElliottKasoar commented
(Following earlier discussion with @jatkinson1000 and @TomMelt where I think we concluded that we want to store the processed .f90 files, as well as the .fypp files)

I'm not sure if you had something like this in mind already, but we could potentially do something similar to [cp2k](https://www.cp2k.org/dev:fypp), which seems to place the compiled .f90 files in an /obj directory, potentially making the /src directory less cluttered.

(I haven't seen anywhere actually store the pre-processed files with git, but I think the idea still works.)

2023-11-06 17:31 UTC, jatkinson1000 commented
Yes, #61 opened to log this proposal.

2023-11-17 13:09 UTC, TomMelt commented
@jatkinson1000 @ElliottKasoar , ok I think I have done it. I have a _fortran only_ version of ftorch interface that uses interface function `torch_tensor_from_array` to create a tensor object from any fortran array.

Can you please both take a look? And feel free to try it out on your machines too.

**Caveats**
* `iso_fortran_env` only supports the following types: `int8, int16, int32, int64, real32, real64` not the full list of torch enums e.g, `torch_kUInt8` and `torch_kFloat16`. I have therefore not generated overloaded functions for these data types.
* I have only converted and tested the `resnet_infer_fortran.f90` example. We should look at converting the others and testing before I merge this.
* Also I would like to make sure this doesn't make timings worse :crossed_fingers:

2023-11-18 14:25 UTC, jatkinson1000 reviewed
Thanks for this @TomMelt.

This is only an interim review as there's a lot to unpack here.
I thought I'd voice things in stages as I work through them.

So far I have:
- Compiled and built this version of FTorch on M2 Mac (gfortran, Apple clang)
- Build and run exercise 2 (Resnet) using your updated code and this version of the library
- Generated FORD docs for this updated version of the libaray

Observations:
- Documentation is now very messy - I'm looking if FORD can generate interface docs.
- I would suggest we rename the functions from e.g. `torch_tensor_from_array_int16_1` to `torch_tensor_from_array_int16_1d` as I think it makes it clearer what the suffix is.
- [ ] Documentation needs updating with fypp install/run instructions
- [ ] We discussed a git hook to generate the ftorch

Other comments:
- [ ] I agree with not supporting non-Fortran types, but we should note this in longer docs
- I agree with fypp and f90 being alongside one another in src/
- Perhaps not for this PR, but we may consider a short explanation of the `sp` precision syntax.

I'll start a closer look at the code now and make a few additions as suitable.

2023-11-18 18:04 UTC, jatkinson1000 commented
Having been through and generated a pre-commit hook to check fypp is generated accordingly I realised I forgot that pre-commit hooks cannot be shared between users or stored as part of the git repo. Therefore I will add an action to check instead, and instructions for developers to add the pre-commit hook manually.

2023-11-18 20:05 UTC, jatkinson1000 commented
Now happy with the workflow.
Slightly watered down from the original proposal, but the best we can do with GitHub I think.
It compares the result of fypp generated code to the existing `ftorch.f90`, and fails if they do not match.

This does not stop people from pushing mismatching code or modifying `ftorch.f90` directly, but such a situation should become apparent when conducting a code review and this check will ensure the pair of files match as a first line of defense.

I have included a more powerful pre-commit hook in the main repo (could move elsewhere?) that will enforce these things for developers. I am happy (with someone else checking) to say this now closes #61

2023-11-18 20:26 UTC, jatkinson1000 commented
Updated the README such that merging this will also close #57 
Would appreciate a second pair of eyes on this.

This will need amending further if we make a decision about simplifying the indexing as well as per #56

2023-11-18 20:29 UTC, jatkinson1000 commented
Since fypp is not a required dependency to run I suggest we move description of how to install this (and use the git hook) to a 'developers'' section of the documentation in #53

2023-11-18 20:38 UTC, jatkinson1000 commented
I'm going to pause here for now, but it would be great if we can get this merged in time for the talk!
Doing so I think requires:
- [ ] Updating examples (I agree with preserving one to demonstrate using blob)
- [ ] Updating benchmarks and timing checks (@ElliottKasoar)
- [ ] Checking GPU functionality (@ElliottKasoar)

We should also consider if we want to make the strides an optional argument (#56), but given the size of this PR this should perhaps be done as another feature. Changing them to be optional should be possible in a backwards compatible way I'd hope.

Once this is clear I'd like to complete #53 in some form, maybe #48, and try to get some MiMA numbers.
And sort some slides I guess...

2023-11-20 17:47 UTC, ElliottKasoar reviewed
This isn't entirely newly introduced by these changes (e.g. [torch_tensor_from_blob](https://github.com/Cambridge-ICCS/FTorch/blob/main/src/ftorch.f90#L48) vs [torch_from_blob_C](https://github.com/Cambridge-ICCS/FTorch/blob/main/src/ftorch.f90#L62)) but something to consider is adding a bit more consistency between the order of parameters.

For example, `layout` and `device` are switched changing from `torch_tensor_from_blob(data, ndims, tensor_shape, dtype, device, layout)` to `torch_tensor_from_array(data_in, layout, c_device)`.

Particularly for integer arguments, this could be easy to miss.

2023-11-21 08:16 UTC, jatkinson1000 commented
Great point, and I agree @ElliottKasoar

2023-11-21 11:25 UTC, ElliottKasoar commented
> I'm going to pause here for now, but it would be great if we can get this merged in time for the talk! Doing so I think requires:
> 
> 
>     * [ ]  Updating benchmarks and timing checks (@ElliottKasoar)
> 
>     * [ ]  Checking GPU functionality (@ElliottKasoar)
> 
> 
> We should also consider if we want to make the strides an optional argument (#56), but given the size of this PR this should perhaps be done as another feature. Changing them to be optional should be possible in a backwards compatible way I'd hope.
> 
> Once this is clear I'd like to complete #53 in some form, maybe #48, and try to get some MiMA numbers. And sort some slides I guess...

Changes tested on CSD3 GPUs, and no apparent change in timings seen on CPU or GPU.

My PR will also hopefully have an example of [cgdrag](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/time-full-program/benchmark_cgdrag/benchmarker_cgdrag_torch.f90) with both `from_array` (explicit reshaping) and `from_blob` (implicit reshaping), so that can potentially be adapted/used to inform new examples.

2023-11-21 12:51 UTC, jatkinson1000 requested changes
I'm now happy with this, but agree we should standardise inputs to functions.
@ElliottKasoar @TomMelt How do we feel about the following precedence order:
- input data
- device
- layout
- ndims
- tensor_shape
- dtype

This keeps required first, and anticipates future development when `layout` may become optional.

I'd also suggest the 'c-only-example' becomes its own pull request and we merge this once the above is done.

2023-11-21 14:12 UTC, ElliottKasoar commented
> I'm now happy with this, but agree we should standardise inputs to functions. @ElliottKasoar @TomMelt How do we feel about the following precedence order:
> 
> * input data
> * device
> * layout
> * ndims
> * tensor_shape
> * dtype
> 
> This keeps required first, and anticipates future development when `layout` may become optional.
> 
> I'd also suggest the 'c-only-example' becomes its own pull request and we merge this once the above is done.

I think @TomMelt mentioned to me earlier deliberately putting `device` at the end, as it's a bit more detached from specification of the tensor (please correct me if I'm misquoting), but I think I agree with @jatkinson1000 that the more optional the argument, the lower the precedence, probably makes more sense.

2023-11-21 15:08 UTC, jatkinson1000 commented
OK, that makes sense.
I have standardised, so how does that look now?
Kept device at the end which I think makes sense (this is also what Torch does).

2023-11-21 15:32 UTC, ElliottKasoar requested changes
I think we discussed this, but is there a reason to keep test_tensor.f90 still?

I would maybe either update the instances of [torch_tensor_from_blob](https://github.com/Cambridge-ICCS/FTorch/blob/mwe-fypp-preprocessor/examples/tensor_tests/test_tensor.f90#L40) or delete it, but otherwise looks great!

2023-11-21 16:09 UTC, ElliottKasoar commented on pre-commit
I'm wondering if this should be in utils, especially since most users don't need to worry about it?

2023-11-21 16:09 UTC, ElliottKasoar commented on pre-commit
> +set -eo pipefail
I seem to get an error using this (after moving it into /.git/hooks): `.git/hooks/pre-commit: 9: set: Illegal option -o pipefail`. Any idea why?

2023-11-21 16:15 UTC, ElliottKasoar commented on pre-commit
> +set -eo pipefail
Should it be `#!/bin/bash` rather than `#!/bin/sh`?

2023-11-21 16:33 UTC, jatkinson1000 commented on pre-commit
I also thought that, but then decided `utils/` was more for toold and utilities that most users _do_ want.
I'm not sure top is the best place for it, but also not sure it's `utils/`.

2023-11-21 16:43 UTC, ElliottKasoar commented on pre-commit
Hmm true, maybe something like a `.githooks` directory?

I haven't really come across hooks before, but I take it you haven't come across any particular convention?

2023-11-21 16:48 UTC, ElliottKasoar commented on pre-commit
> +set -eo pipefail
Removing the line doesn't seem to change the error, unfortunately.

(Changing it to `#!/bin/bash` did work)

It definitely needs execution rights, as removing them (`chmod -x`) meant that `git commit` ignored the hook, so we definitely need to ensure it's present, but it doesn't fix the option error.

2023-11-21 17:02 UTC, jatkinson1000 commented on pre-commit
> +set -eo pipefail
I think let's make it `#!/bin/bash` in that case.

2023-11-21 17:06 UTC, jatkinson1000 commented on pre-commit
That seems a sensible suggestion to me. Done.

2023-11-21 17:22 UTC, ElliottKasoar requested changes
I'm not sure the .githooks directory was added in your last commit @jatkinson1000.

2023-11-21 17:27 UTC, jatkinson1000 commented
> I'm not sure the .githooks directory was added in your last commit @jatkinson1000.

Uuurrgghhhhhh I just used `mv` instead of `git mv`.
Thank you.
Should be sorted now.

2023-11-21 17:34 UTC, ElliottKasoar approved these changes

2023-11-21 18:11 UTC, TomMelt commented
> OK, that makes sense. I have standardised, so how does that look now? Kept device at the end which I think makes sense (this is also what Torch does).

I think we need the following order for `torch_tensor_from_blob`:
- input data
- ndims
- tensor_shape
- layout/strides
- dtype
- device

This will then match the order of args in `torch_from_blob_c`
```fortran
function torch_from_blob_c(data, ndims, tensor_shape, strides, dtype, device) result(tensor_p)
```
and those in `torch_tensor_from_array`
```fortran
function torch_tensor_from_array(data_in, layout, c_device) result(tensor)
```

What do you think @jatkinson1000 ? If you are happy I have a commit waiting to be pushed that fixes it

2023-11-21 18:22 UTC, jatkinson1000 commented
That sounds sensible to me!

2023-11-21 18:35 UTC, merged