Update resnet18.py
Cambridge-ICCS/FTorch pull request #63
Opened 2023-11-08 08:21 UTC by aysha2016

Command-Line Arguments: Modify the script to accept command-line arguments, making it more versatile. Users can specify the input image file, working precision, and model type as command-line arguments.

2023-11-08 11:40 UTC, jatkinson1000 requested changes
Hi @aysha2016 Thank you for using FTorch and opening up a community contribution.

Unfortunately I was unable to run this code due to a few suprious `"""` and indentation errors. I have noted a few, but not all, in your code.

Please could you update to something that runs on your system and then let us know, and we will then conduct a more in-depth review.

2023-11-08 11:40 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> +"""
This is creating errors

2023-11-08 11:40 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> +"""
This isn't indented properly.

2023-11-08 11:40 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
>          torch_precision = torch.float32
Dead code shouldn't be left in - it has been superseded by the below.

2023-11-08 11:40 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> +    plt.show()
This is great as long as the user has a system that can execute `plt.show()`. Perhaps there could be an option for show with it being switched off by default. We can assume if a user has downloaded and provided an image they know what it looks like.

2023-11-24 08:56 UTC, jatkinson1000 requested changes
Thank you for pushing your changes to this PR @aysha2016 and thank you for addressing some of the comments from the previous review.

Unfortunately you have removed some things that we would prefer to be left in the code such as documentation and evaluation functions. If you could put these back and update the PR it would be appreciated.

We have updated the main branch of the code since you opened this PR, so you may want to consider syncing your fork to get the latest code.

Finally, please also update the local README for this exercise to specify how the user could/should run the code with your argparse additions.

Many thanks.

2023-11-24 08:56 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> -    # See: https://pytorch.org/vision/0.8/models.html
The docstrings are important to help users understand the code, so please leave them in (this applies to the below docstrings as well.)

2023-11-24 08:56 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> -    np_input.tofile("data/image_tensor.dat")
Please keep the images and data files in the `data/` subdirectory.

2023-11-24 08:56 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> -        )
This function is useful for allowing users to view and evaluate the results, so please keep it in the code.

2023-11-24 08:56 UTC, jatkinson1000 commented on examples/2_ResNet18/resnet18.py
> +    run_model(rn_model, np_precision, args.image_path)
Please include some checks/help for the image_path variable (see https://docs.python.org/3/library/argparse.html#example for a good example)

2023-11-26 12:11 UTC, jatkinson1000 reviewed
Thank you, this is starting to look better.
Please let us know in the comment and by requesting a re-review when you are ready.
Please add some instructions to the README in exercise 2 to describe how to run the code in its new format.

Brief comments:
- please keep data files in the `data/` directory
- Consider updating your fork to bring it in line with the latest changes

2023-12-05 20:10 UTC, jatkinson1000 commented
Thanks @aysha2016 
I can't see your updates here, but it looks like you have made them in the `main` branch of [your fork](https://github.com/aysha2016/FTorch).
If you merge `main` into the `aysha2016-patch-1` branch they should appear here.

2023-12-06 14:00 UTC, jatkinson1000 requested changes
Thank you @aysha2016
The precision command line argument is looking great!
A few general comments below, and specific points noted in the code.

This PR is currently [failing the automated checks](https://github.com/Cambridge-ICCS/FTorch/actions/runs/7114466328/job/19368931377?pr=63) as it does not conform to the [black](https://black.readthedocs.io/en/stable/index.html) code style.
You can remedy this by running
```
pip install black
black myfile.py
```
to reformat python file `myfile.py` and then committing the result.

Please see in the code for other comments.

2023-12-06 14:00 UTC, jatkinson1000 commented on examples/2_ResNet18/README.md
> +Replace /path/to/your/image.jpg with the path to the image you want to classify.
Could you make the example run on `data/dog.jpg` to ensure that it matches the example results below, and then move your explanation of how to specify other images to the "Further Options" section at the end of this file please?

2023-12-14 08:50 UTC, aysha2016 commented on examples/2_ResNet18/resnet18.py
> +    args = parser.parse_args()
Many thanks.  I have removed the --model_type command line argument.

2023-12-14 08:51 UTC, aysha2016 commented on examples/2_ResNet18/resnet18.py
> +    run_model(rn_model, np_precision, args.image_path,"data/categories.txt")
I have made the suggested change

2023-12-14 08:52 UTC, aysha2016 commented on examples/2_ResNet18/resnet18.py
> +def run_model(model: torch.nn.Module, precision: type, image_filename: str, categories_filename: str) -> None:
I have made the suggested change

2023-12-14 08:53 UTC, aysha2016 commented on examples/2_ResNet18/resnet18.py
> -    # See: https://pytorch.org/vision/0.8/models.html
included again .

2023-12-14 08:53 UTC, aysha2016 commented on examples/2_ResNet18/resnet18.py
> +    np_input.tofile("image_tensor.dat")
I have made the suggested change

2023-12-14 08:53 UTC, aysha2016 commented on examples/2_ResNet18/README.md
> +python resnet18.py /path/to/your/image.jpg --precision fp32 --model_type resnet18
I have made the suggested change.

2023-12-14 08:56 UTC, aysha2016 commented on examples/2_ResNet18/README.md
> +To save the pretrained ResNet-18 model to TorchScript run the modified version of the pt2ts.py` tool :
Many thanks for addressing the issue. I have made changes as per your suggestion.

Aysha

2024-03-27 00:51 UTC, jatkinson1000 commented
Closing this as stale.

2024-03-27 00:51 UTC, closed without merging