Cmake fix
Cambridge-ICCS/FTorch pull request #67
Opened 2023-11-19 16:00 UTC by jatkinson1000

I believe this closes #14 

Namely the comments below the main one regarding install location.
cmake files are now placed at `$CMAKE_INSTALL_PREFIX/lib/cmake/FTorch/` allowing CMake to locate things automatically if passed `CMAKE_PREFIX_PATH = $CMAKE_INSTALL_PREFIX`.

This means we no longer specify the `FTorch_DIR` argument, instead using `CMAKE_PREFIX_PATH` as standard.

Regarding the other items in #14:
- Documentation has no dependencies as it is deployed by a GitHub action
- Examples exist as standalone items with their own CMake - I would argue that they should not in any way be combined with the main CMakeLists
- Currently no testing dependencies (or testing 😬) but we can make this a flag option when we write them.

Tested on apple M1 mac to build library, install, and build/run examples 1 and 2.
Would appreciate someone else replicating on a different system.

2023-11-20 11:12 UTC, ElliottKasoar commented
Both examples seem to work for me on WSL (Ubuntu 20.04)

I assume we're not updating the work-in-progress example for now?

Worth noting we'll need to update the benchmarking repo too.

2023-11-20 11:24 UTC, SimonClifford reviewed
Not sure about glob patterns in `LDFLAGS` suggestions in README.md

2023-11-20 11:24 UTC, SimonClifford commented on README.md
> +LDFLAGS += -L<path/to/install/location>/lib* -lftorch
Can you do this?  I know it's a suggestion in documentation but if a user puts a `*` there expecting it to work, I don't think it will, will it?

2023-11-20 11:24 UTC, SimonClifford commented on README.md
> +export LD_LIBRARY_PATH = $LD_LIBRARY_PATH:<path/to/install/location>/lib*
As above.

2023-11-20 11:27 UTC, jatkinson1000 commented on README.md
> +LDFLAGS += -L<path/to/install/location>/lib* -lftorch
Thanks.
I wasn't too sure about this as it seems system-dependent.
Sometimes it's `lib`, sometimes `lib64` etc.
I meant to use `*` as 'there may be something or nothing here' like the CMake documentation does, but I agree that isn't clear.
Do you have any suggestions?

2023-11-20 11:45 UTC, TomMelt requested changes
looks good but not happy with *

2023-11-20 11:48 UTC, SimonClifford commented on README.md
> +LDFLAGS += -L<path/to/install/location>/lib* -lftorch
But these are the directions for Make.  I _think_ if you say `/foo/bar/lib*' you'll add a directory called `/foo/bar/lib*` (because `*` is a legitimate character in pathnames!).

I think you can specify `lib` and maybe add a comment that says:
`# or lib64` or something like that.

2023-11-21 13:46 UTC, ElliottKasoar requested changes

2023-11-21 13:46 UTC, ElliottKasoar commented on README.md
> +Note: If you used the `CMAKE_INSTALL_PREFIX` argument when
Minor/stylistic but maybe add an indent/italic as we do elsewhere for notes?

2023-11-21 13:46 UTC, ElliottKasoar commented on README.md
> +[building and installing the library](#libaray-installation) above then you should use
```suggestion
[building and installing the library](#library-installation) above then you should use
```

2023-11-21 13:59 UTC, ElliottKasoar approved these changes

2023-11-21 14:32 UTC, TomMelt approved these changes

2023-11-21 14:41 UTC, merged