Update README.md to give some extra guidance to Mac OS X users
Cambridge-ICCS/FTorch pull request #75
Opened 2023-11-28 17:08 UTC by dorchard

This is something I noticed when building on my M1 Mac. I've added a little guidance (a note) to suggest the most likely succesfull path to building for other such users.

2023-11-28 17:46 UTC, ElliottKasoar commented on README.md
> +	  Note __Mac OS X users__ are more likely to have success using the approach of pointing cmake at python install of PyTorch.
Possibly unnecessarily specific, but it might be worth clarifying that this applies to ARM-based Macs specifically (I assume).

I would maybe also consider moving this to a (very short!) macOS support section, similar to for [Windows](https://github.com/Cambridge-ICCS/FTorch/tree/dorchard-patch-1#windows-support), as otherwise this is very easy to miss, with pip-installed PyTorch as the recommended/tested approach (pending @jatkinson1000's testing)?

2023-11-28 19:45 UTC, jatkinson1000 requested changes
It looks like libtorch is currently only available in binary form for x86 architectures according to https://pytorch.org/ (though there are some unofficial binaries going around) which I think is the root of the issues here. It's strange, as there must be an arm build that comes as part of the pip install.

As such I don't think this should be communicated in its current form at the moment as there could well be an arm binary in future.
I would agree with @ElliottKasoar that it is worth perhaps noting in an "Apple Silicon Support" section that at time of writing there is no binary and a pip install of torch is required for apple silicon macs.

Related - I am interested to see if it is possible to use MPS from libtorch.

2023-11-29 09:38 UTC, dorchard commented
Thanks. I've made an "Apple Silicon support" section similar to the Windows one that explains the situation in more detail.

2023-11-29 10:58 UTC, jatkinson1000 approved these changes
Yep, I am happy with this now.
Since it matches @ElliottKasoar's suggestion I will approve and merge now.
Worth keeping in mind to amend if an arm binary does appear in future.

2023-11-29 10:59 UTC, merged