Unit tests (using pFunit)
Cambridge-ICCS/FTorch pull request #76
Opened 2023-11-28 17:48 UTC by dorchard

I have started putting in the infrastructure for us to write some unit tests using pFunit.

Create simple unit tests for main functions
- [ ] Make the cmake portable; I fought a bit, but I don't know enough cmake. We need to be able to link the include directories for ftorch. At the moment the library and include paths need to be specified.
- [ ] Test `torch_tensor_from_blob` (WIP)
- [ ]  Test `torch_tensor_from_array`

Other things using `torch_module_forward` could be better with an integration test since it will need a lot of setup code anyway.

2023-11-28 17:55 UTC, dorchard commented
tests/test_ftorch.pf gives a start of a unit test for `torch_tensor_from_blob`

2024-04-13 21:10 UTC, jatkinson1000 commented
Has this gone anywhere, or has it stagnated?

As far as I see it tests are the only thing preventing us from making a JOSS submission, and with at least 3 research projects using FTorch that are likely to publish soon this is now a matter of urgency.

For something minimal I was thinking we could have some CMake Test to build and run the SimpleNet example for a few different inputs and check the outputs are correct as an integration test.

2024-04-15 10:28 UTC, dorchard commented
There's a start here, but it got a bit stalled as I could use some help with the cmake. Perhaps someone is able to work with me on this? @TomMelt ?

2024-04-15 11:52 UTC, jatkinson1000 commented
Great, thanks @dorchard
Proposal from the morning is to briefly pause on this in favour of integration tests in # so we can make a JOSS submission, then return to this. We can certainly take a look and help with cmake, and the integration tests will use cmake so you might find those useful.

2024-04-17 06:39 UTC, TomMelt commented
Hi @dorchard I'm more than happy to help with the `CMake` side of things. Let me know when is convenient.

2024-11-15 14:07 UTC, dorchard commented
@jwallwork23 I rebased off `main` for you.

2024-11-15 15:57 UTC, jwallwork23 commented on .github/workflows/test_suite.yml
> +          cmake ..
`-DCMAKE_INSTALL_PREFIX=...` to override the build path to avoid version number.

2024-11-15 17:21 UTC, jwallwork23 commented on .github/workflows/test_suite.yml
> +          cmake ..
I tried this but it didn't seem to help. Pinning the pFUnit version for now (see https://github.com/Cambridge-ICCS/FTorch/pull/76/commits/fdc4d0566bbc87d3d91f3f82555671f854608f1e).

2024-11-15 17:24 UTC, jwallwork23 commented
Perhaps this PR could just set up the infrastructure and add tests for the tensor constructors and we could address writing unit tests for the rest of FTorch in a follow-up PR?

2024-11-18 10:01 UTC, dorchard commented on src/test/unit/test_constructors.pf
> +  ! @assertTrue(tensor%p /= c_null_ptr) ! FIXME: compiler not happy with this
I think the idiomatic way to do this would be
```suggestion
  ! @assertTrue(associated(tensor%p))
```

2024-11-18 10:04 UTC, dorchard commented on src/test/unit/test_constructors.pf
> +  ! @assertTrue(tensor%p /= c_null_ptr) ! FIXME: compiler not happy with this
(although I'm not quite sure how that works with the ffi to C).

2024-11-18 10:21 UTC, jwallwork23 commented on src/test/unit/test_constructors.pf
> +  ! @assertTrue(tensor%p /= c_null_ptr) ! FIXME: compiler not happy with this
Thanks for the suggestion but yeah it gives
```
/home/joe/software/FTorch/src/test/unit/test_constructors.pf:38:29:

   38 |   @assertTrue(associated(tensor%p))
      |                             1
Error: ‘pointer’ argument of ‘associated’ intrinsic at (1) must be a POINTER
```

But if I use `@assertTrue(c_associated(tensor%p))` where `c_associated` is from the `iso_c_binding` then it's all good. Thanks!

2024-11-18 10:23 UTC, dorchard commented on src/test/unit/test_constructors.pf
> +  ! @assertTrue(tensor%p /= c_null_ptr) ! FIXME: compiler not happy with this
Ah right yes, that handles the way to do it across the FFI- cool!

2024-11-18 10:29 UTC, jwallwork23 commented on src/test/unit/test_constructors.pf
> +  ! @assertTrue(tensor%p /= c_null_ptr) ! FIXME: compiler not happy with this
Fixed in https://github.com/Cambridge-ICCS/FTorch/pull/76/commits/fbd869905008b9279dddd77ded5f1947f13a1c61.

2024-11-19 10:27 UTC, jwallwork23 commented
Interestingly, I needed to set the integer kind to get these tests working on my Ubuntu laptop, too (see https://github.com/Cambridge-ICCS/FTorch/pull/76/commits/c30bc218440d641e52ead288abbf4dc5e13c9a93). I'll update this to follow @TomMelt's 32-bit int approach once #137 is merged.

2024-11-25 10:53 UTC, jwallwork23 commented
[Rebased on top of main to bring in linting changes]

2024-12-16 11:34 UTC, jwallwork23 commented
Thanks for the tips @TomMelt - with a few tweaks the tests now pass on Ubuntu. There's a build fail in the Windows CI, although I didn't edit the Windows CI workflow or the part of the CMakeLists that it errors at. Do you have any thoughts on what's gone wrong?
https://github.com/Cambridge-ICCS/FTorch/actions/runs/12351579042/job/34466833553?pr=76

2024-12-18 10:41 UTC, jwallwork23 commented
Merged in the Windows fix from #207 in https://github.com/Cambridge-ICCS/FTorch/pull/76/commits/23ce977bfa9068797a4f9be0ea183f6290e2f54a. Turned off unit testing for Windows in https://github.com/Cambridge-ICCS/FTorch/pull/76/commits/f1e9add826c8b02f87e6d53f1380d7d7b55f3521.

2024-12-18 10:48 UTC, jwallwork23 commented
@dorchard I can't add you as a reviewer because you authored the initial commits, but any comments you have would be appreciated.

2024-12-23 10:10 UTC, jwallwork23 commented
Went through this in the meeting today; up-to-date with `main` and ready for review.

2025-01-06 13:34 UTC, dorchard commented
I'm having issues building the unit tests, e.g.:
```
[ 37%] Building Fortran object test/unit/CMakeFiles/test_constructors.dir/test_constructors.F90.o
/Users/dorchard/Documents/iccs/FTorch/src/build/test/unit/test_constructors.F90:10:7:

   10 |   use pFUnit
      |       1
```
I am using pfunit-4.10 whose mod files seem to be named `funit.mod` instead (changing `use pFunit` to `use funit` in test_constructors.f90 makes things build...) Has there been a breaking interface change for pfunit? Is it because I built pfUnit skipping the OpenMP and MPI builds I wonder? I can't seem to identify whether this actually changes the mod file though. Maybe I am missing something obvious in the build setup.

2025-01-06 13:39 UTC, jwallwork23 commented
> I'm having issues building the unit tests, e.g.:
> 
> ```
> [ 37%] Building Fortran object test/unit/CMakeFiles/test_constructors.dir/test_constructors.F90.o
> /Users/dorchard/Documents/iccs/FTorch/src/build/test/unit/test_constructors.F90:10:7:
> 
>    10 |   use pFUnit
>       |       1
> ```
> 
> I am using pfunit-4.10 whose mod files seem to be named `funit.mod` instead (changing `use pFunit` to `use funit` in test_constructors.f90 makes things build...) Has there been a breaking interface change for pfunit? Is it because I built pfUnit skipping the OpenMP and MPI builds I wonder? I can't seem to identify whether this actually changes the mod file though. Maybe I am missing something obvious in the build setup.

Yes, you need to install with MPI to get pFUnit (p for parallel). However, I realised that isn't actually used at present so switched to `use FUnit` in the current tests, so that should work for you.

2025-01-06 13:55 UTC, jwallwork23 commented
Note that I've opened #216 to fix a related issue with `torch_tensor_from_array`. It will merge into this PR.

2025-01-06 14:17 UTC, jwallwork23 commented on src/test/unit/test_constructors.pf
> +
Great suggestion, thanks!

2025-01-06 14:20 UTC, jwallwork23 commented on src/test/unit/test_constructors.pf
> +  integer(kind=c_int64_t), parameter :: tensor_layout(ndims) = [2,3]
Hm well we seem to use `tensor_shape` in the source code and `tensor_layout` in the examples. So perhaps we should pick one and stick with it?

2025-01-06 14:27 UTC, dorchard commented on src/test/unit/test_constructors.pf
> +  integer(kind=c_int64_t), parameter :: tensor_layout(ndims) = [2,3]
Hm. Well we seem to use `tensor_layout` as well when talking about the description of index order (i.e., in the third parameter to `torch_tensor_from_array`) - see above in the other tests. Could there be some ambiguity here?

2025-01-06 14:28 UTC, jwallwork23 commented
> I think this is a good starting point for our unit tests. I had one suggestion. Having a 3D test would also be good I think, at least on the torch_tensor_from_array side.

Good suggestion. I added this in 4dad25e945000be5ae005b4f9f56608d8686bdc8, which required extending the `assert_allclose` test util to cover the 3D case.

2025-01-06 14:45 UTC, jatkinson1000 commented on src/test/unit/test_constructors.pf
> +  integer(kind=c_int64_t), parameter :: tensor_layout(ndims) = [2,3]
`layout` in the source and `tensor_layout` in the examples are the index order - used to handle `i,j,k` vs `k,j,i` or other more exotic options for strided access.

`tensor_shape` in the source is for `[ni, nj, nk]`

So I think I agree with @dorchard  here.
@jwallwork23 I just checked the examples and they seem consistent to me - the only time we use a "`shape`" is in 2 where I think the usage matches the source and the above suggestion.

2025-01-06 14:51 UTC, jwallwork23 commented on src/test/unit/test_constructors.pf
> +  integer(kind=c_int64_t), parameter :: tensor_layout(ndims) = [2,3]
Ah okay I misread the source. Cool, will make this change then.

2025-01-06 15:40 UTC, dorchard commented
Looks good to go for me!

2025-01-06 15:46 UTC, TomMelt requested changes
Thanks @jwallwork23 and @dorchard , this is great. Really good to get unit tests into Ftorch :raised_hands: 

FWIW, I tested locally on my machine and it works great. Only change I had to make was to the `CMAKE_PREFIX_PATH` as mentioned in my review.

Once that is changed I think its HOTTOGO :fire:  (sorry couldn't resist a Chappell Roan reference)

2025-01-06 15:46 UTC, TomMelt commented on .github/workflows/test_suite_ubuntu.yml
> +            -DCMAKE_PREFIX_PATH="${PFUNIT_DIR}:${Torch_DIR}" \
I am not sure how this works. I think it should be
```suggestion
            -DCMAKE_PREFIX_PATH="${PFUNIT_DIR};${Torch_DIR}" \
```

See [here](https://cmake.org/cmake/help/v3.0/command/list.html) for info on CMake lists.

On my machine it won't run unless I make it a semicolon.

2025-01-06 15:51 UTC, jwallwork23 commented on .github/workflows/test_suite_ubuntu.yml
> +            -DCMAKE_PREFIX_PATH="${PFUNIT_DIR}:${Torch_DIR}" \
Huh, I wasn't aware of that. Thanks!

2025-01-06 15:57 UTC, TomMelt approved these changes
HOTTOGO :fire:

2025-01-06 16:36 UTC, jatkinson1000 approved these changes
Thanks @jwallwork23, this is fantastic.
Since others have run the unit tests and we have been through them together I am going to trust that they are all OK since I can't run locally on my mac right now.

My comments/suggestions focus more on the docs and infrastructure and are minor.

2025-01-06 16:36 UTC, jatkinson1000 commented on .github/workflows/test_suite_ubuntu.yml
> +          cmake -DMPI=YES ..
What is `MPI=YES` needed for? I can't find reference to it in the pFunit documentation.

2025-01-06 16:36 UTC, jatkinson1000 commented on .github/workflows/test_suite_ubuntu.yml
> +          # TODO: How can we avoid the pFUnit version ending up in the install path?
Do you want to leave this as a `TODO`, or convert it to a `NOTE`?

2025-01-06 16:36 UTC, jatkinson1000 commented on .github/workflows/test_suite_ubuntu.yml
> +          # TODO: How can we avoid the pFUnit version ending up in the install path?
```suggestion
          # NOTE: The pFUnit version (pinned during installation above) is used in the install path.
```

2025-01-06 16:36 UTC, jatkinson1000 commented on pages/testing.md
> +expressions.
```suggestion
and run and their outputs are analysed.
```
I think we removed the checking of regular expressions to make the testing process robust across platforms?

2025-01-06 16:36 UTC, jatkinson1000 commented on pages/testing.md
> +- `run_test_suite.bat` for Windows
Is it worth noting here that unit tests not run on Windows?

2025-01-06 16:36 UTC, jatkinson1000 commented on .github/workflows/test_suite_ubuntu.yml
> +          cmake -DMPI=YES ..
```suggestion
          cmake ..
```

I think this would be OK, but can't test locally on my machine at present.
Looking at [the docs](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/tree/v4.10.0) it seems there is a `SKIP_MPI` option which we would not want if building with MPI support.

2025-01-06 16:36 UTC, jatkinson1000 commented on src/test/README.md
> +directory to the `CMAKE_PREFIX_PATH` when building FTorch.
Worth noting here that these are not available on Windows?

2025-01-06 16:36 UTC, jatkinson1000 commented on src/test/README.md
> +- `run_test_suite.bat` for windows
```suggestion
- `./run_test_suite.sh` for unix (Mac and Linux)
- `run_test_suite.bat` for Windows
```
Consistent with your changes above.

2025-01-06 16:36 UTC, jatkinson1000 commented on src/test/unit/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.12)
```suggestion
cmake_minimum_required(VERSION 3.15)
```
Make this 3.15 to match `src/CMakeLists.txt`?
Optional, as I suppose the "minimum" for this particular script is 3.12, but on the assumption we are building on the same environment as main we need 3.15 there.

2025-01-06 16:38 UTC, jatkinson1000 commented on .github/workflows/test_suite_ubuntu.yml
> +          # TODO: How can we avoid the pFUnit version ending up in the install path?
See suggestion below doing this.

2025-01-06 16:38 UTC, jatkinson1000 commented on .github/workflows/test_suite_ubuntu.yml
> +          cmake -DMPI=YES ..
See suggestion below removing this.

2025-01-06 16:44 UTC, jatkinson1000 commented on pages/testing.md
> +- `run_test_suite.bat` for Windows
```suggestion
- `run_test_suite.bat` for Windows (note this will only run the integration tests, not unit tests.)
```

2025-01-06 16:47 UTC, jatkinson1000 commented on src/test/README.md
> +directory to the `CMAKE_PREFIX_PATH` when building FTorch.
```suggestion
directory to the `CMAKE_PREFIX_PATH` when building FTorch.

Note that the unit tests are currently only available on Unix based systems, not Windows.
```

2025-01-06 17:12 UTC, jwallwork23 commented
Thanks again everyone! Merging now :rocket:

2025-01-06 17:12 UTC, merged